### ISSUE TITLE
reindex keyword issue

### ISSUE THREAD

**Issue by manoukis** [manoukis/outbreak-reporter#1]
So close! I was able to run pipeline for a new outbreak until the very last step.. I am getting the following error on running make_report.py
```
Traceback (most recent call last):
  File "../bin/make_report.py", line 471, in <module>
    sys.exit(Main(argv=None))
  File "../bin/make_report.py", line 160, in Main
    args.DDc_per_generation)
  File "/home/manoukis/outbreak-reporter-master/bin/temperature_functions.py", line 99, in compute_BMDD_Fs
    e[~np.isnan(tmp)] = dd.index[tmp[~np.isnan(tmp)].astype(int)]
  File "/share/opt/python/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/series.py", line 938, in __setitem__
    setitem(key, value)
  File "/share/opt/python/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/series.py", line 929, in setitem
    self._where(~key, value, inplace=True)
  File "/share/opt/python/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/generic.py", line 7619, in _where
    transpose=self._AXIS_REVERSED)
  File "/share/opt/python/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3696, in putmask
    return self.apply('putmask', **kwargs)
  File "/share/opt/python/miniconda3/envs/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3578, in apply
    copy=align_copy)
TypeError: reindex() got an unexpected keyword argument 'axis'
```
pandas is version 0.23, python 3.6.5. The error seems to be in this line:
```
e[~np.isnan(tmp)] = dd.index[tmp[~np.isnan(tmp)].astype(int)]
```
looking at tmp, I see 
```
tmp = np.searchsorted(cDD, cDD+(cumdd_threshold)-dd['DD'], side='left').astype(float)
tmp[tmp>=len(tmp)] = np.nan
```
Travis, can you save me?

**Comment by travc** [comment]
Ok.  Should be fixed now.
